@startuml alur
title 
Alur Aplikasi E-Commerce 
dengan C++
end title
allow_mixing

class Pengguna {
    - id: int
    - nama: string
    - alamat: string
    - nomorTelepon: int
}
class Penjual {
    - namaToko: string
    - deskripsiToko: string
    - produkProduk: Barang{...}
    - 
}
class Pembeli {
    - sudahBayar: bool
    - metodeBayar: string
    - keranjang: array
}

class Barang {
    - id: int
    - name: string
    - jumlah: int
    - harga: float
    - namaToko: string
    - alamatToko: string
    - jumlahBintang: string
    - jumlahTerjual: string
}

actor adalahPembeli
actor adalahPenjual
collections dagangan
queue koleksi

Pengguna --> Penjual
note top of Penjual: penjual turunan \ndari pengguna
Pengguna --|> Pembeli
note top of Pembeli: pembeli turunan \ndari pengguna
Barang --|> dagangan
adalahPembeli -- Pembeli
adalahPenjual -- Penjual

adalahPembeli --> dagangan
adalahPenjual <-- dagangan
note bottom of dagangan: Pembeli membeli dagangan yang dijual Penjual
@enduml