@startuml kerja
title "Alur beli barang di e-commerce"
skinparam defaultTextAlignment center
skinparam backgroundColor white
skinparam handwritten false

start
:Masuk ke website dari browser anda;

if (Terdaftar?) then (Yes)
    :Login;
else (No)
    :Daftar;
    :Login;
endif

if (Cocok?) then (No)
    :Masukkan Username atau password salah;
    stop
else (Yes)
    :Halaman Utama;
endif

:Pilih Barang;

partition "Kategori Produk" {
    :Electronics|
    :Smart Home|
    :Baby|
    :Automotive|
    :Books|
    :Toys and Households|
    :Computers|
    :Fashion|
    :Home And Kitchen|
    :Pet Supplies|
    :Sport and Outdoors|
}

:Pilih (untuk semua kategori);

:Masukan ke keranjang;

:Melihat ulang Pesanan;

:Masukan informasi Pengiriman;

if (Apakah informasi yang dimasukkan benar?) then (Yes)
    :Pilih Metode pembayaran;
    :Dapatkan Pesanan;
    stop
else (No)
    :Merubah informasi Tersebut dengan Benar;
    :Pilih Metode pembayaran;
    :Dapatkan Pesanan;
    stop
endif

@enduml